### ISSUE TITLE
Aborted (core dumped)

### ISSUE THREAD

**Issue by certik** [travisdowns/avx-turbo#6] opened 2018-08-28 16:22 UTC
As of 1bcf79a21bf82cbee890fa19d40840ba4e75adb1:
```
$ sudo ./avx-turbo 
Running as root     : [YES]
CPU pinning enabled : [YES]
CPU supports AVX2   : [NO ]
CPU supports AVX-512: [NO ]
cpuid = eax = 7, ebx = 832, ecx = 832, edx = 0
tsc_freq = 0.1 MHz (from cpuid leaf 0x15)
Will test up to 32 CPUs
avx-turbo: avx-turbo.cpp:200: uint64_t aperf_ghz::read(uint32_t): Assertion `res == 0' failed.
Aborted (core dumped)
```
Perhaps my CPU is not supported. I use Ubuntu 16.04 and:
```
$ cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 62
model name      : Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz
stepping        : 4
microcode       : 0x42c
cpu MHz         : 1322.851
cache size      : 20480 KB
physical id     : 0
siblings        : 16
core id         : 0
cpu cores       : 8
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm epb ibrs ibpb stibp kaiser tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass
bogomips        : 5187.19
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:
...
```

**Comment by travisdowns** [comment] 2018-08-28 16:28
I see the problem, but can you try running it as non-root, and update the
results?

It this a VM or QEMU or something like that? The frequency reported by
could is 0.1 MHz which I've seen from valgrind for example.

**Comment by travisdowns** [comment] 2018-08-28 17:55
@certik  part of the problem is that I assume the `/msr` filesystem is available, but it probably isn't on your machine.

What does:

`lsmod | grep msr`

report?

If it reports nothing, if you do a `modprobe msr` does the error go away?

**Comment by certik** [comment] 2018-08-28 18:50
1. If you run it without root, then the answer is: https://gist.github.com/certik/ac64489179e7fb5b26413d109fed2869

2. No, I run it directly in a terminal on real hardware (no VM, no QEMU). Yes, the reported frequency is obviously wrong.

3. Indeed, there is no `/msr` on my machine.

4. `lsmod` does not have `msr` loaded.

5. When I load `msr` using `sudo modprobe msr`, then `lsmod` reports msr.

6. Now it works. I get the following output for `sudo ./avx-turbo`: https://gist.github.com/certik/467f4abef4b94b20ae3c4d013834fcd1. Note that `/msr` is still not available.

**Comment by certik** [comment] 2018-08-28 18:51
Although the frequency is still 0.1 in my output in 6. above.

**Comment by travisdowns** [comment] 2018-08-28 20:33
@certik  - yeah the problem is I'm calculating the frequency from `cpuid` leaf `0x15` but that doesn't exist on this machine. I'm fixing that now.

Note that most of the tests use AVX2 code, but your machine only supports AVX, so you don't see many tests (exactly 1 in fact). I could add some AVX tests (perhaps some of them actually only need AVX, but I just marked them as AVX2).

**Comment by certik** [comment] 2018-08-28 20:40
@travisdowns yeah, do what you think is the best. I was mainly curious about what your program can do, and how you calculate the frequency. I have calculated the frequency in the past by running a benchmark that I trust, typically a memory read benchmark, and then adjusting the frequency until I got exactly 4 double precision reads per cycle (or how many reads can be done on a given processor). Typically on single core that was the posted frequency in `cpuinfo` (2.6GHz) plus 20%. On multiple cores, that "turbo" speed was sometimes less than 20%.

**Comment by travisdowns** [comment] 2018-08-28 20:48
@certik - I am using a couple of approaches to calculate the frequency, with the idea that the more the better in case one of them goes off.

One is the `Mops` column which shows millions of operations per second, which should be the same as `MHz` for single-cycle dependent operations like scalar add. It doesn't work on your box because the TSC calibration was totall wrong so when it tries to convert the timings to Mops you get rounded 0.

This approach doesn't need to use `rdtsc` to do the timing though, you could also use `std::chrono` or `clock_gettime` or whatever other time API is offered, and this would have worked in your case. There is code in avx-turbo to do that, but I didn't enable it yet via a command line option (you can replace use of `RdtscClock` with `StdClock` in the code to do that though).

The other approach I use is to read the APERF/MPERF counters that Intel offers. This is the "official" way to caculate frequency: APERF is "actual clock cycles" and MPERF is reference clock cycles, so an APERF/MPERF ratio something like 1.3 means that you had an average turbo of 30% over reference. You multiply that ratio by the TSC frequency to get the actual frequency over any interval. To read APERF/MPERF I need msr access, and that's what was failing for you (the assertion failure).

Note that you are only supposed to use the APERF/MPERF _ratio_ and never the values by themselves since the absolute values don't have a specific definition, but on all Intel hardware other than weird Phi/KNL type stuff APERF is actually clock cycles and MPERF is actually TSC cycles, so you don't even really need to do the ratio or know the TSC frequency on most boxes.

**Comment by travisdowns** [comment] 2018-08-28 21:59
@certik - can you pull and run again with root and non-root if you have a moment?

I think I've fixed both the underlying issues. You should get basically the same display for root and non-root (only the Mops column) without `modprobe msr` but with `msr` module running you should get the right output (the `A/M MHz` column was reporting zero before because it is based on the TSC value which was being calculated wrong, but it should be fixed).

**Comment by travisdowns** [comment] 2018-08-28 23:42
@certik - I just added a `--warmup-ms` parameter which defaults to 100ms of warmup.

If you get a moment, you could test it and I would be interested to see the results. If you can't be bothered, I understand!

**Closed** 2018-09-08 03:04 UTC
